services:
  fyp-postgres:
    image: postgres:15
    container_name: fyp-postgres
    restart: always
    environment:
      - POSTGRES_DB=fyp
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    networks:
      - fyp-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d fyp"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - fyp-data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  # fyp-backend:
  #   image: hammad1029/fyp-backend:latest
  #   container_name: fyp-backend
  #   ports:
  #     - '3001:3001'
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     fyp-postgres:
  #       condition: service_healthy
  #   env_file:
  #     - /home/hammaduh/dev/fyp/backend/.env
  #   networks:
  #     - fyp-net

  # fyp-frontend:
  #   image: hammad1029/fyp-frontend:latest
  #   container_name: fyp-frontend
  #   ports:
  #     - '3000:3000'
  #   stdin_open: true
  #   tty: true
  #   env_file:
  #     - /home/hammaduh/dev/fyp/mindtrack2/.env
  #   networks:
  #     - fyp-net

volumes:
  fyp-data:
    name: fyp-data

networks:
  fyp-net:
    name: fyp-net
    external: false