services:
  fyp-postgres:
    image: postgres:15
    container_name: fyp-postgres
    restart: always
    environment:
      - POSTGRES_DB=fyp
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d fyp"]
      interval: 5s
      timeout: 2s
      retries: 20
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  # fyp-backend:
  #   image: hammad1029/fyp-backend:latest
  #   container_name: fyp-backend
  #   ports:
  #     - '3001:3001'
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     fyp-postgres:
  #       condition: service_healthy
  #   env_file:
  #     - /home/hammaduh/dev/fyp/backend/.env

  # fyp-frontend:
  #   image: hammad1029/fyp-frontend:latest
  #   container_name: fyp-frontend
  #   ports:
  #     - '3000:3000'
  #   stdin_open: true
  #   tty: true
  #   env_file:
  #     - /home/hammaduh/dev/fyp/mindtrack2/.env

  # fyp-model:
  #   image: hammad1029/fyp-model:latest
  #   container_name: fyp-model
  #   ports:
  #     - '8000:8000'
  #   tty: true
