services:
  institutions-db:
    image: postgres:15
    container_name: institutions-db
    restart: always
    environment:
      - POSTGRES_DB=institutions
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d institutions" ]
      interval: 5s
      timeout: 2s
      retries: 20
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  users-db:
    image: postgres:15
    container_name: users-db
    restart: always
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d users" ]
      interval: 5s
      timeout: 2s
      retries: 20
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  games-db:
    image: postgres:15
    container_name: games-db
    restart: always
    environment:
      - POSTGRES_DB=games
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d games" ]
      interval: 5s
      timeout: 2s
      retries: 20
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  attempts-db:
    image: postgres:15
    container_name: attempts-db
    restart: always
    environment:
      - POSTGRES_DB=attempts
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d attempts"]
      interval: 5s
      timeout: 2s
      retries: 20
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  institutions:
    image: hammad1029/fyp-micro-http-institutions:latest
    container_name: institutions
    ports:
      - "3000:3000"
    depends_on:
      institutions-db:
        condition: service_healthy
    env_file:
      - institutions-env
    restart: always

  users:
    image: hammad1029/fyp-micro-http-users:latest
    container_name: users
    ports:
      - "3001:3000"
    depends_on:
      users-db:
        condition: service_healthy
    env_file:
      - users-env
    restart: always

  games:
    image: hammad1029/fyp-micro-http-games:latest
    container_name: games
    ports:
      - "3002:3000"
    depends_on:
      games-db:
        condition: service_healthy
    env_file:
      - games-env
    restart: always

  attempts:
    image: hammad1029/fyp-micro-http-attempts:latest
    container_name: attempts
    ports:
      - "3003:3000"
    depends_on:
      attempts-db:
        condition: service_healthy
    env_file:
      - attempts-env
    restart: always

  model:
    image: hammad1029/fyp-model:latest
    container_name: model
    ports:
      - '8000:8000'
    tty: true
    stdin_open: true